### PR TITLE
Updated repository requirements and some CS fixes

### PR DESCRIPTION
**Pull request by mmoreram**

### CODE REVIEW

**Comment by mmoreram** [comment]
@egulias WOW, you require a big package of dependencies just for testing? I mean, you need full symfony stack just to test it? It has no sense...

This PR will only make sense if you just plan another kind of tests, without requiring all symfony stack.

Finally, we have removed this dependency from Elcodi project because we've had some composer problems because this requirement. First we need to check that this package only requires used components :)

Thanks

**Comment by egulias** [comment]
I was checking as well. Not really, if you look at the tests, all they seem to need are the Console component and the DIC. May be there is a non-explicit dependency in the FrameworkBundle?

**Comment by mmoreram** [comment]
check you file `appDevDebugProjectContainer`.

There are lot of dependencies just for the test.

**Comment by egulias** [comment]
You are right. I have to clean it up and add dummy classes as listeners instead of the fw ones.

**Comment by mmoreram** [comment]
+1 that's it :) Tell me if you need some help! :D

**Comment by egulias** [comment]
Would really appreciate your help if you have time and want to, I won't have it until the weekend.

**Comment by egulias** [comment]
@mmoreram will you have time for that?

**Comment by mmoreram** [comment]
@egulias I will not. I have not much time for other projects, sorry.

**Comment by egulias** [comment]
Is ok, I wanted to know to organize my weekend.
Thanks!

2014-08-06 16:10 GMT+02:00 Marc Morera notifications@github.com:

**Pull request merged**
